# Generated by Django 3.1.4 on 2020-12-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='use',
            name='operation',
            field=models.CharField(max_length=20),
        ),
    ]
